AWSTemplateFormatVersion: '2010-09-09'
Description: Setup AWS IAM roles for Spinnaker

Parameters:
  EC2KeyPairName:
    Type: String
  SubnetId:
    Type: AWS::EC2::Subnet::Id
  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id

Mappings:
  # ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20190320
  AMI:
    ap-northeast-1:
      AMI: ami-0b86ca67cb64addcf
    ap-northeast-2:
      AMI: ami-0a8c567c2272f6d79
    ap-northeast-3:
      AMI: ami-0b24e5daf582bdc88
    ap-south-1:
      AMI: ami-07c128e60e80e6766
    ap-southeast-1:
      AMI: ami-010162ac5374d76d3
    ap-southeast-2:
      AMI: ami-09e6fd1e6e5bec813
    ca-central-1:
      AMI: ami-0066a22261093fc7a
    eu-central-1:
      AMI: ami-083b8eed05b2a7373
    eu-north-1:
      AMI: ami-851c95fb
    eu-west-1:
      AMI: ami-01bc69b830b49f729
    eu-west-2:
      AMI: ami-04773891d2d406800
    eu-west-3:
      AMI: ami-07eba027bc5ec8e27
    sa-east-1:
      AMI: ami-055021d1882c809af
    us-east-1:
      AMI: ami-06d990a360d7a793c
    us-east-2:
      AMI: ami-0c8b8e32659017cc5
    us-gov-east-1:
      AMI: ami-79d13708
    us-gov-west-1:
      AMI: ami-36bbd557
    us-west-1:
      AMI: ami-0f1d0daf2937d0064
    us-west-2:
      AMI: ami-0b4a4b368aa8bd6f0

Resources:
  SpinnakerDevInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [AMI, !Ref 'AWS::Region', 'AMI']
      InstanceType: "m5.4xlarge"
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            VolumeSize: 100
            DeleteOnTermination: "true"
      IamInstanceProfile: "SpinnakerDevInstanceRole"
      KeyName: !Ref "EC2KeyPairName"
      SecurityGroupIds:
        - !Ref SecurityGroupId
      SubnetId: !Ref SubnetId
      Tags:
        - Key: Name
          Value: SpinnakerDev
      UserData:
          Fn::Base64:
            !Sub |
              #!/bin/bash
              set -ex

              # Install dependencies for localgit installation
              add-apt-repository ppa:openjdk-r/ppa
              apt-get update
              apt-get -y install git curl netcat redis-server openjdk-8-jdk emacs awscli python2.7 python-pip

Outputs:
  SpinnakerDevInstance:
    Value: !Sub ${SpinnakerDevInstance.PublicDnsName}
    Description: 'Spinnaker development instance public name (connect via SSH as user ubuntu)'
